In [1]:
import glob
from bs4 import BeautifulSoup
import re
from tqdm import tqdm
import pandas as pd
from datetime import datetime, timedelta
import calendar
from collections import Counter
import requests
import multiprocessing as mp
from multiprocessing import Pool
import time
from datetime import datetime

# WEB CRAWL
import urllib
import random
import datetime as dt
from itertools import cycle

## Functions

In [4]:
def convert_date(date):
    # Remove special characters
    date = re.sub('[^a-z0-9]', " ", date)
    try:
        # ASSUMING dd MMM
        # Extract day
        day_start = re.search('^\d+', date).start()
        day_end = re.search('^\d+', date).end()
        day = date[day_start:day_end]
        if len(day) == 1:
            day = "0"+day
        # Extract month
        date_wo_day = date[day_end:].strip()
        month_start = re.search('^\w+', date_wo_day).start()
        month_end = re.search('^\w+', date_wo_day).end()
        month = date_wo_day[month_start:month_end]
        if "jan" in str(month):
            month = "01"
        if "feb" in str(month):
            month = "02"
        if "mar" in str(month):
            month = "03"
        if "apr" in str(month):
            month = "04"
        if "may" in str(month):
            month = "05"
        if "jun" in str(month):
            month = "06"
        if "jul" in str(month):
            month = "07"
        if "aug" in str(month):
            month = "08"
        if "sep" in str(month):
            month = "09"
        if "oct" in str(month):
            month = "10"
        if "nov" in str(month):
            month = "11"
        if "dec" in str(month):
            month = "12"

        full_date = day+"."+month+".2019"
        if len(full_date) == 10:
            return datetime.strptime(full_date, '%d.%m.%Y').date()
        else:
            return "nil"
    except:
        return "nil"

In [12]:
def convert_time(time, post_time):
    return_time = "nil"
    time_original = str(re.sub(r'[.:]', '', time)).strip()
    time_original = str(re.sub(r'^([a-zA-Z]+ ){1,}', '', time_original)).strip()
    time_original = str(re.sub(r'\d+\-', '', time_original)).strip()
    
    # ASSUME NUM PM
    if bool(re.search(r'^\d+ ?pm', time_original)):
        time = time_original.replace("pm", "").strip()
        time = str(time)
        # If 1,2,3,4,5,6,7,8,9
        if len(str(time)) == 1:
            time = int(time)
            if time == 1:
                return_time = "13:00"
            if time == 2:
                return_time = "14:00"
            if time == 3:
                return_time = "15:00"
            if time == 4:
                return_time = "16:00"
            if time == 5:
                return_time = "17:00"
            if time == 6:
                return_time = "18:00"
            if time == 7:
                return_time = "19:00"
            if time == 8:
                return_time = "20:00"
            if time == 9:
                return_time = "21:00"
        # If 10,11,12
        if len(str(time)) == 2:
            time = int(time)
            if time == 10:
                return_time = "22:00"
            if time == 11:
                return_time = "23:00"
            if time == 12:
                return_time = "12:00"
        # If single hour (eg. 1) and minutes (eg. 15)
        if len(str(time)) == 3:
            hour = int(time[0])
            if hour == 1:
                return_time = "13:"+time[1:]
            if hour == 2:
                return_time = "14:"+time[1:]
            if hour == 3:
                return_time = "15:"+time[1:]
            if hour == 4:
                return_time = "16:"+time[1:]
            if hour == 5:
                return_time = "17:"+time[1:]
            if hour == 6:
                return_time = "18:"+time[1:]
            if hour == 7:
                return_time = "19:"+time[1:]
            if hour == 8:
                return_time = "20:"+time[1:]
            if hour == 9:
                return_time = "21:"+time[1:]
        # If double hour (eg. 11) and minutes (eg. 30)
        if len(str(time)) == 4:
            hour = int(time[0:2])
            if hour == 10:
                return_time = "22:"+time[2:]
            if hour == 11:
                return_time = "23:"+time[2:]
            if hour == 12:
                return_time = "12:"+time[2:]
    
    # ASSUME NUM AM
    if bool(re.search(r'^\d+ ?am', time_original)):
        time = time_original.replace("am", "").strip()
        time = str(time)
        # If 1,2,3,4,5,6,7,8,9
        if len(str(time)) == 1:
            time = int(time)
            if time == 1:
                return_time = "01:00"
            if time == 2:
                return_time = "02:00"
            if time == 3:
                return_time = "03:00"
            if time == 4:
                return_time = "04:00"
            if time == 5:
                return_time = "05:00"
            if time == 6:
                return_time = "06:00"
            if time == 7:
                return_time = "07:00"
            if time == 8:
                return_time = "08:00"
            if time == 9:
                return_time = "09:00"
        # If 10,11,12
        if len(str(time)) == 2:
            time = int(time)
            if time == 10:
                return_time = "10:00"
            if time == 11:
                return_time = "11:00"
            if time == 12:
                return_time = "00:00"
        # If single hour (eg. 1) and minutes (eg. 15)
        if len(str(time)) == 3:
            hour = int(time[0])
            if hour == 1:
                return_time = "01:"+time[1:]
            if hour == 2:
                return_time = "02:"+time[1:]
            if hour == 3:
                return_time = "03:"+time[1:]
            if hour == 4:
                return_time = "04:"+time[1:]
            if hour == 5:
                return_time = "05:"+time[1:]
            if hour == 6:
                return_time = "06:"+time[1:]
            if hour == 7:
                return_time = "07:"+time[1:]
            if hour == 8:
                return_time = "08:"+time[1:]
            if hour == 9:
                return_time = "09:"+time[1:]
        # If double hour (eg. 11) and minutes (eg. 30)
        if len(str(time)) == 4:
            hour = int(time[0:2])
            if hour == 10:
                return_time = "10:"+time[2:]
            if hour == 11:
                return_time = "11:"+time[2:]
            if hour == 12:
                return_time = "00:"+time[2:]
    
    # ASSUME NO PM OR AM
    if bool(re.search(r'^\d+$', time_original)):
        time = str(time_original).strip()
        # If single digit
        if len(time) == 1:
            time = int(time)
            post_hour = post_time[:2]
            if int(post_hour) >= 12:
                if time == 1:
                    return_time = "13:00"
                if time == 2:
                    return_time = "14:00"
                if time == 3:
                    return_time = "15:00"
                if time == 4:
                    return_time = "16:00"
                if time == 5:
                    return_time = "17:00"
                if time == 6:
                    return_time = "18:00"
                if time == 7:
                    return_time = "19:00"
                if time == 8:
                    return_time = "20:00"
                if time == 9:
                    return_time = "21:00"
            else:
                if time == 1:
                    return_time = "01:00"
                if time == 2:
                    return_time = "02:00"
                if time == 3:
                    return_time = "03:00"
                if time == 4:
                    return_time = "04:00"
                if time == 5:
                    return_time = "05:00"
                if time == 6:
                    return_time = "06:00"
                if time == 7:
                    return_time = "07:00"
                if time == 8:
                    return_time = "08:00"
                if time == 9:
                    return_time = "09:00"
        # If double digits
        if len(str(time)) == 2:
            time = int(time)
            post_hour = post_time[:2]
            if int(post_hour) >= 12:
                if time == 10:
                    return_time = "22:00"
                if time == 11:
                    return_time = "23:00"
                if time == 12:
                    return_time = "12:00"
            else:
                if time == 10:
                    return_time = "10:00"
                if time == 11:
                    return_time = "11:00"
                if time == 12:
                    return_time = "00:00"    
        # If three digtis
        if len(str(time)) == 3:
            hour = int(str(time)[0])
            post_hour = post_time[:2]
            if int(post_hour) >= 12:
                if hour == 1:
                    return_time = "13:"+time[1:]
                if hour == 2:
                    return_time = "14:"+time[1:]
                if hour == 3:
                    return_time = "15:"+time[1:]
                if hour == 4:
                    return_time = "16:"+time[1:]
                if hour == 5:
                    return_time = "17:"+time[1:]
                if hour == 6:
                    return_time = "18:"+time[1:]
                if hour == 7:
                    return_time = "19:"+time[1:]
                if hour == 8:
                    return_time = "20:"+time[1:]
                if hour == 9:
                    return_time = "21:"+time[1:]
            else:
                if hour == 1:
                    return_time = "01:"+time[1:]
                if hour == 2:
                    return_time = "02:"+time[1:]
                if hour == 3:
                    return_time = "03:"+time[1:]
                if hour == 4:
                    return_time = "04:"+time[1:]
                if hour == 5:
                    return_time = "05:"+time[1:]
                if hour == 6:
                    return_time = "06:"+time[1:]
                if hour == 7:
                    return_time = "07:"+time[1:]
                if hour == 8:
                    return_time = "08:"+time[1:]
                if hour == 9:
                    return_time = "09:"+time[1:]
        # If four digtis
        if len(str(time)) == 4:
            hour = int(str(time)[0:2])
            post_hour = post_time[:2]
            if int(post_hour) >= 12:
                if hour >= 12:
                    return_time = str(hour)+":"+str(time)[2:]
                if hour == 10:
                    return_time = "22:"+time[2:]
                if hour == 11:
                    return_time = "23:"+time[2:]
                if hour == 0:
                    return_time = "00:"+time[2:]
            else:
                if hour <= 12:
                    if len(str(hour)) == 1:
                        return_time = "0"+str(hour)+":"+str(time)[2:]
                    else:
                        return_time = str(hour)+":"+str(time)[2:]
                if hour == 0:
                    return_time = "00:"+time[2:]
                if hour == 10:
                    return_time = "10:"+time[2:]
                if hour == 11:
                    return_time = "11:"+time[2:]
                if hour == 12:
                    return_time = "00:"+time[2:]
        
    return return_time

## Process Data

### Read Files

In [6]:
html_files_old = glob.glob("./telegram_chat_export_beginning_19sep/*.html")
print("Number of files: ", len(html_files_old))
print(html_files_old[:10])
print()

html_files_new = glob.glob("./telegram_chat_export_13oct_10dec/*.html")
print("Number of files: ", len(html_files_new))
print(html_files_new[:10])

Number of files:  257
['./telegram_chat_export_beginning_19sep\\messages.html', './telegram_chat_export_beginning_19sep\\messages10.html', './telegram_chat_export_beginning_19sep\\messages100.html', './telegram_chat_export_beginning_19sep\\messages101.html', './telegram_chat_export_beginning_19sep\\messages102.html', './telegram_chat_export_beginning_19sep\\messages103.html', './telegram_chat_export_beginning_19sep\\messages104.html', './telegram_chat_export_beginning_19sep\\messages105.html', './telegram_chat_export_beginning_19sep\\messages106.html', './telegram_chat_export_beginning_19sep\\messages107.html']

Number of files:  160
['./telegram_chat_export_13oct_10dec\\messages.html', './telegram_chat_export_13oct_10dec\\messages10.html', './telegram_chat_export_13oct_10dec\\messages100.html', './telegram_chat_export_13oct_10dec\\messages101.html', './telegram_chat_export_13oct_10dec\\messages102.html', './telegram_chat_export_13oct_10dec\\messages103.html', './telegram_chat_export_13oct_10dec\\messages104.html', './telegram_chat_export_13oct_10dec\\messages105.html', './telegram_chat_export_13oct_10dec\\messages106.html', './telegram_chat_export_13oct_10dec\\messages107.html']

In [7]:
html_files = [*html_files_old, *html_files_new]
print("Total html files: ", len(html_files))

Total html files:  417

### Extract Data from Files

In [64]:
messages_list = []
total_messages = 0

for file in tqdm(html_files):    
    f = open(file, "r", encoding='utf-8')
    chat = f.read()
    soup = BeautifulSoup(chat)
    messages = soup.findAll("div", {"class": "message default clearfix"})
    total_messages += len(messages)

    for message in messages:
        # Get user
        user = message.find("div", {"class": "from_name"}).text.replace("\n", "").strip()
        #print(user)
        # Get post date and time
        post_datetime = message.find("div", {"class": "pull_right date details"}).get("title")
        post_date = post_datetime.split(" ")[0]
        post_time = post_datetime.split(" ")[1]
        #print(post_date)
        #print(post_time)
        # GET MESSAGE
        raw_message = message.find("div", {"class": "text"})
        # Extract text from message
        raw_message = str(raw_message).replace("</div>", "").replace('<div class="text">', "").replace("<strong>", "").replace("</strong>", "").replace("<u>", "").replace("</u>", "").strip().lower()
        # Tokenize text
        raw_message_tokens = re.sub(r'(<br/> ?){2,}', '<br/>', raw_message).split("<br/>")

        # Variable flag for actual ride request
        is_request = False
        # Get user type
        if(bool(re.search(r'hitchers? looking', raw_message_tokens[0]))):
            user_type = "hitcher"
            is_request = True
        elif(bool(re.search(r'driver? looking', raw_message_tokens[0]))):
            user_type = "driver"
            is_request = True
        else:
            user_type = "nil"

        # PROCESS MESSAGE CONTENT IF IT IS ACTUALLY A REQUEST
        if(is_request):
            # Blank place holder
            pick_up = "nil"
            drop_off = "nil"
            request_date = "nil"
            request_time = "nil"
            number_of_pax = "nil"
            request_date_normalised = "nil"
            request_time_normalised = "nil"
            day = "nil"
            # ------------------

            # Extract pick up location assuming it is always the second token
            try:
                pick_up_tokens = str(raw_message_tokens[1]).split(":")
            except:
                pass
            try:
                if "pick" in pick_up_tokens[0]:
                    pick_up = pick_up_tokens[1].strip()
            except:
                pick_up_tokens = str(raw_message_tokens[1]).split(" ")
                if "pick" in pick_up_tokens[0]:
                    pick_up = " ".join(pick_up_tokens[1:])
                else:
                    pass

            # Extract drop off location assuming it is always the third token
            try:
                drop_off_tokens = str(raw_message_tokens[2]).split(":")
            except:
                pass
            try:
                if "drop" in drop_off_tokens[0]:
                    drop_off = drop_off_tokens[1].strip()
            except:
                drop_off_tokens = str(raw_message_tokens[2]).split(" ")
                if "drop" in drop_off_tokens[0]:
                    drop_off = " ".join(drop_off_tokens[1:])
                else:
                    pass

            # Extract date assuming it is always the fourth token
            try:
                date_tokens = str(raw_message_tokens[3]).split(":")
            except:
                pass
            try:
                if "date" in date_tokens[0]:
                    request_date = date_tokens[1].strip()
            except:
                date_tokens = str(raw_message_tokens[3]).split(" ")
                if "date" in date_tokens[0]:
                    request_date = " ".join(date_tokens[1:])
                else:
                    pass
            if "today" in request_date or "tdy" in request_date:
                request_date = datetime.strptime(post_date, '%d.%m.%Y').date()
            elif "tmr" in request_date or "tomorrow" in request_date:
                today_date = datetime.strptime(post_date, '%d.%m.%Y').date()
                tomorrow_date = today_date + timedelta(days=1)
                request_date = tomorrow_date
            elif request_date == "nil":
                pass
            else:
                request_date = convert_date(request_date)
            
            # Extract time assuming it is always the fifth token
            try:
                time_raw = str(raw_message_tokens[4])
            except:
                pass
            try:
                time = time_raw.replace("time:", "").replace("time :", "").strip()
                time = re.sub(r'[^a-z0-9.-:]', '', time).strip()
                if "now" in time:
                    request_time = post_time[:5]
                else:
                    request_time = convert_time(str(time), post_time)
            except:
                pass
                
            # Extract number of pax assuming it is always the sixth token
            try:
                if "pax" in raw_message_tokens[5]:
                    raw_pax = str(raw_message_tokens[5]).replace("pax:", "").replace("pax", "").replace("pax :", "").replace("pax : ", "").strip()
                    raw_pax = raw_pax.replace(":", "").strip()
                    raw_pax = re.sub(r'\(.*\)', '', raw_pax)
                    raw_pax = re.sub(r'[^a-z0-9- ]', '', raw_pax)
                    raw_pax = raw_pax.strip()
                    if len(raw_pax) == 1:
                        number_of_pax = raw_pax
                    elif len(raw_pax) == 3:
                        number_of_pax = raw_pax
                    else:
                        if bool(re.search(r'^\d+ - \d+$', raw_pax)):
                            number_of_pax = raw_pax.replace(" ", "")
                        if bool(re.search(r'^\d+ to \d+$', raw_pax)):
                            number_of_pax = raw_pax.replace("to", "-")
                            number_of_pax = number_of_pax.replace(" ", "")
            except:
                pass
            
            # If request_date and time is "nil" format of message might be wrong
            if request_date == "nil" or request_time == "nil":
                # Extract time again
                try:
                    time_raw = re.search(r'time\:.*\<br\/\>', raw_message).group()
                    time = time_raw.split("<br/>")[0]
                    time = time.replace("time:", "").strip()  
                    if "now" in time:
                        request_time = post_time[:5]
                    else:
                        request_time = convert_time(str(time), post_time)
                except:
                    pass
                # Extract date again
                try:
                    date_raw = re.search(r'date\:.*\<br\/\>', raw_message).group()
                    request_date = date_raw.split("<br/>")[0]
                    request_date = date.replace("date:", "").strip()
                    if "today" in request_date or "tdy" in request_date:
                        request_date = datetime.strptime(post_date, '%d.%m.%Y').date()
                    elif "tmr" in request_date or "tomorrow" in request_date:
                        today_date = datetime.strptime(post_date, '%d.%m.%Y').date()
                        tomorrow_date = today_date + timedelta(days=1)
                        request_date = tomorrow_date
                    else:
                        request_date = convert_date(request_date)
                except:
                    if request_time != "nil":
                        request_date = datetime.strptime(post_date, '%d.%m.%Y').date()
                # Extract pax again
                try:
                    if bool(re.search(r'pax:.*\<br\/\>', raw_message)):
                        raw_pax = re.search(r'pax:.*\<br\/\>', lol).group()
                        raw_pax = raw_pax.split("<br/>")[0]
                        raw_pax = raw_pax.replace("pax:", "").strip()
                    if bool(re.search(r'pax:.*$', lol)):
                        raw_pax = re.search(r'pax:.*$', lol).group()
                        raw_pax = raw_pax.replace("pax:", "").strip()
                except:
                    pass
            
            #--------------------NORMALISE DATA---------------------
            
            # Normalise date and time
            try:
                date_time = datetime.strptime(str(request_date)+" "+request_time, '%Y-%m-%d %H:%M')
                approx = round(date_time.minute/30.0) * 30
                date_time = date_time.replace(minute=0)
                date_time += timedelta(seconds=approx*60)
                request_date_normalised = date_time.date()
                request_time_normalised = date_time.strftime('%H:%M')
            except:
                pass
            
            # Add day to data eg. dd-mm-yyyy = wed
            try:
                my_date = datetime.strptime(str(request_date_normalised), '%Y-%m-%d')
                day = calendar.day_name[my_date.weekday()].lower()
            except:
                pass
            
            # Store structured message into dictionary
            message_data = {
                'user' : user,
                'post_date' : post_date,
                'post_time' : post_time,
                'raw_message' : raw_message,
                'user_type' : user_type,
                'pick_up' : pick_up,
                'drop_off' : drop_off,
                'request_date' : request_date,
                'request_date_normalised' : request_date_normalised,
                'request_time' : request_time,
                'request_time_normalised' : request_time_normalised,
                'day' : day,
                'number_of_pax' : number_of_pax
            }
            messages_list.append(message_data)

100%|████████████████████████████████████████████████████████████████████████████████| 417/417 [05:49<00:00,  1.09it/s]

### Stats

In [65]:
print("Total number of messages: \t\t", total_messages)
print("Total number of actual messages: \t", len(messages_list))
print()
print("Percentage of actual messages: \t", round((len(messages_list)/total_messages)*100, 2), "%")

Total number of messages: 		 376598
Total number of actual messages: 	 360464

Percentage of actual messages: 	 95.72 %

### Convert Data to DataFrame

In [ ]:
data = pd.DataFrame(messages_list)
data.head()
data.to_csv("./data/sg_hitch_data_raw_updated.csv")

### Filter out Corrupted Data

In [2]:
data = pd.read_csv("./data/sg_hitch_data_raw_updated.csv", index_col=0)

# Filter out corrupted request time
clean_data_rt = data[data.request_time_normalised != "nil"]
print("Removed", len(data)-len(clean_data_rt), "corrupted request time")
# Filter out corrupted request date
clean_data_rd = clean_data_rt[clean_data_rt.request_date_normalised != "nil"]
print("Removed", len(clean_data_rt)-len(clean_data_rd), "corrupted request date")
# Filter out corrupted pick up
clean_data_pu = clean_data_rd[clean_data_rd.pick_up != "nil"]
print("Removed", len(clean_data_rd)-len(clean_data_pu), "corrupted pick up")
# Filter out corrupted drop off
clean_data_do = clean_data_pu[clean_data_pu.drop_off != "nil"]
print("Removed", len(clean_data_pu)-len(clean_data_do), "corrupted drop off")

Removed 18292 corrupted request time
Removed 0 corrupted request date
Removed 318 corrupted pick up
Removed 2341 corrupted drop off

In [3]:
clean_data = clean_data_do
print("Number of requests left: ", len(clean_data))
print()
print("Percentage of non-corrupted data: ", round(len(clean_data)/len(data)*100, 2), "%")

Number of requests left:  339513

Percentage of non-corrupted data:  94.19 %

In [4]:
clean_data.head()

,day,drop_off,number_of_pax,pick_up,post_date,post_time,raw_message,request_date,request_date_normalised,request_time,request_time_normalised,user,user_type
1,tuesday,bedok reservoir,nil,tuas area,26.02.2019,14:55:47,driver looking for hitchers<br/>pick up: tuas ...,2019-02-26,2019-02-26,18:15,18:00,xoxoxo,driver
2,tuesday,off - ntu,nil,up - mountbatten mrt,26.02.2019,15:00:23,hitcher looking for drivers<br/>pick up - moun...,2019-02-26,2019-02-26,17:00,17:00,Amanda,hitcher
3,tuesday,north-east,nil,bedok/tamp/pasir ris/eunos,26.02.2019,15:39:19,driver looking for hitchers<br/>pick up: bedok...,2019-02-26,2019-02-26,16:00,16:00,J,driver
4,tuesday,north-east or east,nil,jurong,26.02.2019,18:12:47,driver looking for hitchers<br/>pick up: juron...,2019-02-26,2019-02-26,18:12,18:00,Colonel Ronald Silver,driver
7,tuesday,suss,nil,jurong west,26.02.2019,23:50:17,hitcher looking for drivers <br/>pick up: juro...,2019-02-26,2019-02-26,07:30,07:30,a. Lee,hitcher

### Normalise Data

In [60]:
# Clean up pick_up and drop_off
def clean_location(loc):
    # Split multiple nearby locations to use first
    if '/' in loc:
        loc = loc.split('/')[0].strip()
    # Replace short forms
    clean = re.sub(r'\,', ' ', loc)
    clean = re.sub(r'  ', ' ', clean)
    clean = re.sub(r'\(.*\)', '', clean)
    clean = re.sub(r'\<.*\>', '', clean)
    clean = re.sub(r'\<|\>', '', clean)
    clean = re.sub(r'\[.*\]', '', clean)
    clean = re.sub(r'\barea\b$', '', clean)
    clean = re.sub(r'\bblock\b', '', clean)
    clean = re.sub(r'\bblk\b', '', clean)
    clean = re.sub(r'\rd\b', 'road', clean)
    clean = re.sub(r'\bave\b', 'avenue', clean)
    clean = re.sub(r'\bamk\b', 'ang mo kio', clean)
    clean = re.sub(r'\bcck\b', 'choa chu kang', clean)
    clean = re.sub(r'\btpy\b', 'toa payoh', clean)
    clean = re.sub(r'\byck\b', 'yio chu kang', clean)
    clean = re.sub(r'^vivo$', 'vivo city', clean)
    clean = re.sub(r'\btamp\b', 'tampines', clean)
    clean = re.sub(r'\bseng kang\b', 'sengkang', clean)
    clean = re.sub(r'\bcq\b', 'clarke quay', clean)
    clean = re.sub(r'\bwlds\b', 'woodlands', clean)
    clean = re.sub(r'^\bwoodland\b$', 'woodlands', clean)
    clean = re.sub(r'^\bsim\b$', 'singapore institute of management', clean)
    return clean.strip()

pick_up = clean_data['pick_up'].tolist()
drop_off = clean_data['drop_off'].to_list()

pick_up_clean = []
drop_off_clean = []

for pu in tqdm(pick_up):
    pick_up_clean.append(clean_location(str(pu)))
    
for do in tqdm(drop_off):
    drop_off_clean.append(clean_location(str(do)))

100%|██████████| 339513/339513 [00:04<00:00, 74995.23it/s]
100%|██████████| 339513/339513 [00:04<00:00, 74917.13it/s]

In [61]:
print(Counter(pick_up_clean).most_common(20))
print()
print(Counter(drop_off_clean).most_common(20))

[('woodlands', 10057), ('yishun', 8468), ('sengkang', 7876), ('tampines', 7764), ('punggol', 6238), ('hougang', 6020), ('choa chu kang', 5850), ('ang mo kio', 5549), ('pasir ris', 5407), ('jurong west', 4235), ('bedok', 3986), ('jurong', 3864), ('sembawang', 3307), ('bukit batok', 3296), ('bukit panjang', 3025), ('town', 2203), ('clarke quay', 2196), ('toa payoh', 1928), ('serangoon', 1812), ('clementi', 1753)]

[('anywhere', 9975), ('woodlands', 9294), ('yishun', 7988), ('tampines', 7308), ('sengkang', 7119), ('hougang', 6003), ('punggol', 5971), ('choa chu kang', 5686), ('ang mo kio', 5269), ('pasir ris', 4964), ('jurong west', 3978), ('jurong', 3889), ('bedok', 3720), ('town', 3163), ('bukit panjang', 3070), ('sembawang', 2930), ('bukit batok', 2870), ('clementi', 1936), ('west', 1887), ('toa payoh', 1833)]

In [7]:
# Check if values change
for i in range(5004,5010):
    print("Org: ", pick_up[i])
    print("Clean: ", pick_up_clean[i])
    print()

Org:  wlds 731628
Clean:  woodlands 731628

Org:  star vista
Clean:  star vista

Org:  jurong
Clean:  jurong

Org:  760236
Clean:  760236

Org:  jurong east/bukit batok
Clean:  jurong east

Org:  vivo
Clean:  vivo city

In [62]:
# Add columns to dataframe
data_normalised = clean_data.assign(pick_up_clean=pick_up_clean,
                                    drop_off_clean=drop_off_clean)
data_normalised.head()

,day,drop_off,number_of_pax,pick_up,post_date,post_time,raw_message,request_date,request_date_normalised,request_time,request_time_normalised,user,user_type,pick_up_clean,drop_off_clean
1,tuesday,bedok reservoir,nil,tuas area,26.02.2019,14:55:47,driver looking for hitchers<br/>pick up: tuas ...,2019-02-26,2019-02-26,18:15,18:00,xoxoxo,driver,tuas,bedok reservoir
2,tuesday,off - ntu,nil,up - mountbatten mrt,26.02.2019,15:00:23,hitcher looking for drivers<br/>pick up - moun...,2019-02-26,2019-02-26,17:00,17:00,Amanda,hitcher,up - mountbatten mrt,off - ntu
3,tuesday,north-east,nil,bedok/tamp/pasir ris/eunos,26.02.2019,15:39:19,driver looking for hitchers<br/>pick up: bedok...,2019-02-26,2019-02-26,16:00,16:00,J,driver,bedok,north-east
4,tuesday,north-east or east,nil,jurong,26.02.2019,18:12:47,driver looking for hitchers<br/>pick up: juron...,2019-02-26,2019-02-26,18:12,18:00,Colonel Ronald Silver,driver,jurong,north-east or east
7,tuesday,suss,nil,jurong west,26.02.2019,23:50:17,hitcher looking for drivers <br/>pick up: juro...,2019-02-26,2019-02-26,07:30,07:30,a. Lee,hitcher,jurong west,suss

In [340]:
# Get location that are not planning area names
df = pd.read_csv("./data/planning_area_population.csv")
planning_areas = df['name'].tolist()

data_no_pa = data_normalised[~data_normalised['pick_up_clean'].isin(planning_areas)]

data_no_pa_final = data_no_pa[~data_no_pa['drop_off_clean'].isin(planning_areas)]

print("Length: ", len(data_no_pa_final))
print()
data_no_pa_final.head()

Length:  188209

,day,drop_off,number_of_pax,pick_up,post_date,post_time,raw_message,request_date,request_date_normalised,request_time,request_time_normalised,user,user_type,pick_up_clean,drop_off_clean,pick_up_geo,drop_off_geo
1,tuesday,bedok reservoir,nil,tuas area,26.02.2019,14:55:47,driver looking for hitchers<br/>pick up: tuas ...,2019-02-26,2019-02-26,18:15,18:00,xoxoxo,driver,tuas area,bedok reservoir,nil,nil
2,tuesday,off - ntu,nil,up - mountbatten mrt,26.02.2019,15:00:23,hitcher looking for drivers<br/>pick up - moun...,2019-02-26,2019-02-26,17:00,17:00,Amanda,hitcher,up - mountbatten mrt,off - ntu,nil,nil
4,tuesday,north-east or east,nil,jurong,26.02.2019,18:12:47,driver looking for hitchers<br/>pick up: juron...,2019-02-26,2019-02-26,18:12,18:00,Colonel Ronald Silver,driver,jurong,north-east or east,nil,nil
13,wednesday,paya lebar or nearby,nil,plaza sing,27.02.2019,08:33:33,driver looking for hitchers<br/>pick up: plaza...,2019-02-27,2019-02-27,08:33,08:30,Geraldine,driver,plaza sing,paya lebar or nearby,nil,nil
21,wednesday,parklane,nil,changi airport terminal 1,27.02.2019,12:39:01,hitcher looking for driver <br/>pick up: chang...,2019-02-27,2019-02-27,14:00,14:00,我是小肥 💛,hitcher,changi airport terminal 1,parklane,nil,nil

In [63]:
#from fake_useragent import UserAgent
#ua = UserAgent()
#HEADER = {'User-Agent': ua.random}
HEADERS_LIST = [
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13',
    'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201',
    'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
    'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre'
]

PROXY_URL = 'https://free-proxy-list.net/'

def get_proxies():
    response = requests.get(PROXY_URL)
    soup = BeautifulSoup(response.text, 'lxml')
    table = soup.find('table',id='proxylisttable')
    list_tr = table.find_all('tr')
    list_td = [elem.find_all('td') for elem in list_tr]
    list_td = list(filter(None, list_td))
    list_ip = [elem[0].text for elem in list_td]
    list_ports = [elem[1].text for elem in list_td]
    list_proxies = [':'.join(elem) for elem in list(zip(list_ip, list_ports))]
    return list_proxies

In [64]:
# Get lat-long of location pick_up_clean and drop_off_clean
def get_address(row_index):
    time.sleep(0.1)
    #-----PARAMETERS------
    HEADER = {'User-Agent': random.choice(HEADERS_LIST)}
    proxy = next(proxy_pool)
    #---------------------
    
    pick_up_geo = "nil"
    drop_off_geo = "nil"
    
    if bool(re.search(r'\d{6}', data_normalised.iloc[row_index]['pick_up_clean'])):
        pu_location = re.search(r'\d{6}', data_normalised.iloc[row_index]['pick_up_clean']).group()
    else:
        pu_location = data_normalised.iloc[row_index]['pick_up_clean']
    onemap_url = "https://developers.onemap.sg/commonapi/search"
    onemap_params = {'searchVal' : pu_location, 'returnGeom' : "Y", 'getAddrDetails' : "Y"}
    r = requests.get(url = onemap_url, params = onemap_params, headers=HEADER, proxies={"http": proxy}, timeout=60)
    data = r.json()
    try:
        lat = data['results'][0]['LATITUDE']
        long = data['results'][0]['LONGTITUDE']
        lat_long = lat+","+long
        pick_up_geo = lat_long
    except:
        pass
    
    if bool(re.search(r'\d{6}', data_normalised.iloc[row_index]['drop_off_clean'])):
        do_location = re.search(r'\d{6}', data_normalised.iloc[row_index]['drop_off_clean']).group()
    else:
        do_location = data_normalised.iloc[row_index]['drop_off_clean']
    onemap_params = {'searchVal' : do_location, 'returnGeom' : "Y", 'getAddrDetails' : "Y"}
    r = requests.get(url = onemap_url, params = onemap_params, headers=HEADER, proxies={"http": proxy}, timeout=60)
    data = r.json()
    try:
        lat = data['results'][0]['LATITUDE']
        long = data['results'][0]['LONGTITUDE']
        lat_long = lat+","+long
        drop_off_geo = lat_long
    except:
        pass
    
    result_string = str(row_index)+","+pu_location+","+pick_up_geo+","+do_location+","+drop_off_geo
    
    f = open("./data/geoloc_2.txt", "a")
    f.write("%s\n" %result_string)
    print(result_string)
    return pd.DataFrame([[row_index, pu_location, pick_up_geo, do_location, drop_off_geo]], columns=['index', 'pick_up_loc', 'pick_up_geo', 'drop_off_loc', 'drop_off_geo'])

In [71]:
geo = pd.read_csv("./data/geoloc.txt")
len(geo)

149724

In [76]:
data_geocode

,index,pick_up_loc,pick_up_geo,drop_off_loc,drop_off_geo
0,139776,53 south bridge road,"1.28718977995276,103.848406930083",520892,"1.3490128285900602,103.929242816227"
0,139777,suntec city tower 3,nil,119618,"1.29114551964664,103.775485210879"
0,139778,liang court,"1.29149019892639,103.84466893511299",ubi avenue 1,"1.32652255789937,103.89920714261"
0,139779,689671,"1.3879732576111299,103.74461846013901",24 jalan nipah,"1.32592332741719,103.953261215349"
0,139780,orchard clark quey,nil,punggol,"1.40546002750829,103.898354203231"
...,...,...,...,...,...
0,139771,sembawang,"1.4505243561844299,103.829006229545",sengkang,"1.38315380470819,103.89238167637801"
0,139772,63 tanjong pagar,"1.2782699195602099,103.843963149811",640725,"1.34545354960103,103.69771962383601"
0,139773,choa chu kang bukit batok yew tee,nil,anywhere,nil
0,139774,jurong,"1.34390440884759,103.766254087753",pasir ris,"1.3799565415449098,103.96361889803002"
0,139775,51 kent road,"1.3167570723148,103.85110555793399",150125,"1.28593366735428,103.80299973798799"

In [72]:
index_done = geo['row_index'].tolist()

In [73]:
index_left = list(set(range(150000)) - set(index_done))

In [75]:
proxies = get_proxies()
proxy_pool = cycle(proxies)

start = datetime.now()
with Pool(15) as p:
    result = p.map(get_address, index_left)
print("time: ", datetime.now()-start)

data_geocode = pd.concat(result)
#data_geocode.to_csv("./data/sg_hitch_data_geocode.csv")
#data_geocode.head()

139826,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139831,central,1.31194385226653,103.879213380261,west,1.33740588596152,103.736415996185
139791,ntu arc north spine,nil,760260,1.4354775412800402,103.83927653299601
139781,town,1.30923241301234,103.842649053422,east,1.3108349867393,103.92171580265999
139816,prinsep st,1.29970274449064,103.849886983698,tampines,1.35022823751066,103.928412800091
139786,town,1.30923241301234,103.842649053422,punggol sk,1.40648143439085,103.902073294574
139796,orchard,1.3026182214637099,103.829383494413,pioneer,1.3085131714795701,103.674623963707
139801,bedok,1.32368201682055,103.947789319297,serangoon,1.3448920150304198,103.87125222941201
139836,orchard,1.3026182214637099,103.829383494413,jurong west,1.34160326621595,103.70808518963301
139846,novotel,1.2915147818883799,103.84458629833,marine parade,1.3028676454890702,103.90483750033701
139811,bukit panjang hillion mall,nil,yew tee,1.3973210291170202,103.753758637401
139841,orchard,1.3026182214637099,103.829383494413,pioneer,1.3085131714795701,103.674623963707
139821,nsrcc,1.31971039574265,103.97173737638799,sengkanf,nil
139806,320021,1.32615714500421,103.860130769235,730368,1.43294240133529,103.786732547129
139776,53 south bridge road,1.28718977995276,103.848406930083,520892,1.3490128285900602,103.929242816227
139827,novotel,1.2915147818883799,103.84458629833,admiralty,1.4566576383969299,103.81739436132099
139842,389294,1.31222857122099,103.876503775928,tampines,1.35022823751066,103.928412800091
139822,sk,1.3314355925697299,103.841140774921,jurong,1.34390440884759,103.766254087753
139812,yishun,1.41694678230154,103.845000884876,clementi west,1.3265692183209499,103.76241720172101
139832,sembawang,1.4505243561844299,103.829006229545,yishun,1.41694678230154,103.845000884876
139837,one altitude,nil,575728,1.36099060483292,103.828974355886
139797,prinsep st or nearby,nil,jurong west,1.34160326621595,103.70808518963301
139802,059425,1.28417410964979,103.843765102369,530952,1.37529714968238,103.877732108482
139782,airport terminal 2,1.3562397543598301,103.98936496626,circuit road,1.3289684761557,103.886379232388
139777,suntec city tower 3,nil,119618,1.29114551964664,103.775485210879
139807,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139817,yishun,1.41694678230154,103.845000884876,clementi west,1.3265692183209499,103.76241720172101
139792,town,1.30923241301234,103.842649053422,jurong,1.34390440884759,103.766254087753
139847,bait 73 bussorah street,nil,38a zion road,1.2935258705331498,103.830984334167
139787,733573,1.4305017367250201,103.797682947729,460525,1.3346011394176103,103.92944527163799
139823,clarke quay,1.29044567334676,103.84568804993799,pasir ris,1.3799565415449098,103.96361889803002
139843,389294,1.31222857122099,103.876503775928,pasir ris,1.3799565415449098,103.96361889803002
139828,boat quay,1.2881578742698,103.849373215384,anywhere,nil
139813,sembawang,1.4505243561844299,103.829006229545,sengkang,1.38315380470819,103.89238167637801
139803,holland piazza,1.31064349551562,103.795246166084,prince george park residences,1.29079947179946,103.78130451174299
139808,woodlands,1.41520591465648,103.758554325238,town,1.30923241301234,103.842649053422
139833,changi airport terminal 2 arrivals door 2,nil,840 tampines street 82 s,1.35114217702739,103.935616862084
139848,d underground,nil,640427,1.3513137356609801,103.725596710632
139818,bukit batok,1.3508238085532098,103.73826825406601,anywhere,nil
139793,suntec convention centre,1.2936221622883302,103.857252816966,537016,1.34905704486649,103.878113199585
139788,parklane,1.3006510265884599,103.84944198056,clementi,1.2963298251589699,103.7676022071
139838,changi airport terminal 2 arrivals door 3*,nil,840 tampines street 82 s,1.35114217702739,103.935616862084
139783,town,1.30923241301234,103.842649053422,punggol sk,1.40648143439085,103.902073294574
139778,liang court,1.29149019892639,103.84466893511299,ubi avenue 1,1.32652255789937,103.89920714261
139798,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139824,bk eating house boat quay,nil,150125,1.28593366735428,103.80299973798799
139844,520372,1.3564421453905902,103.95809563794201,520266,1.35196574894384,103.950237717969
139829,novotel,1.2915147818883799,103.84458629833,admiralty,1.4566576383969299,103.81739436132099
139814,haig road,1.30945197244195,103.897745585385,bukit batok central,1.34830331812746,103.748999021552
139804,prinsep st or nearby,nil,jurong west,1.34160326621595,103.70808518963301
139809,prinsep st or nearby,nil,jurong west,1.34160326621595,103.70808518963301
139839,389294,1.31222857122099,103.876503775928,tampines,1.35022823751066,103.928412800091
139789,orchard,1.3026182214637099,103.829383494413,anywhere,nil
139834,jurong east,1.34063904358364,103.742474504127,anywhere,nil
139849,dempsey,1.30467342053312,103.809040024736,punggol,1.40546002750829,103.898354203231
139779,689671,1.3879732576111299,103.74461846013901,24 jalan nipah,1.32592332741719,103.953261215349
139794,bukit batok st 31,1.35921822041831,103.74986478923701,t4 airport,1.33859975650386,103.98376378912901
139819,bk eating house boat quay,nil,760361,1.42832475935832,103.845908268643
139799,old airport,1.30854798388123,103.889064718377,bukit batok,1.36053358595052,103.74236455589701
139784,21 jalan tenteram,1.32615714500421,103.860130769235,368 woodlands avenue 1,1.43294240133529,103.786732547129
139845,the mask,nil,6 raffles boulevard,1.29145526802577,103.85700733568001
139830,sembawang,1.4505243561844299,103.829006229545,yishun,1.41694678230154,103.845000884876
139825,holland village mrt,1.31107119772805,103.795769657083,649824,1.34226751765488,103.716270247824
139815,yishun stadium,1.4126536592190702,103.83182042279499,680626,1.39832082870876,103.745878081637
139840,town,1.30923241301234,103.842649053422,jurong west,1.34160326621595,103.70808518963301
139810,786475,1.40462020134182,103.821109809336,518071,1.3720347049909398,103.946401836451
139805,clarke quay,1.29044567334676,103.84568804993799,commonwealth,1.29556628401854,103.806204356557
139850,woodlands,1.41520591465648,103.758554325238,toa payoh,1.33904144822194,103.857955654132
139785,51 kent road,1.3167570723148,103.85110555793399,150125,1.28593366735428,103.80299973798799
139820,bedok,1.32368201682055,103.947789319297,serangoon,1.3448920150304198,103.87125222941201
139835,tampines,1.35022823751066,103.928412800091,west coast,1.29484588174167,103.766282088026
139800,kallang,1.3070669559676298,103.86706973971,anywhere,nil
139795,holland piazza,1.31064349551562,103.795246166084,prince george park,1.29079947179946,103.78130451174299
139790,near novena,nil,near ikea alexandra,nil
139780,orchard clark quey,nil,punggol,1.40546002750829,103.898354203231
139851,liang court,1.29149019892639,103.84466893511299,admiralty,1.4566576383969299,103.81739436132099
139861,liang court,1.29149019892639,103.84466893511299,760927,1.4276746452937998,103.837731455467
139856,jurong,1.34390440884759,103.766254087753,anywhere,nil
139866,orchard,1.3026182214637099,103.829383494413,hg,nil
139881,punggol,1.40546002750829,103.898354203231,upper thomson,1.39758106126826,103.817856949947
139921,clarke quay,1.29044567334676,103.84568804993799,bukit batok,1.36053358595052,103.74236455589701
139916,town,1.30923241301234,103.842649053422,ang mo kio,1.3687783887791,103.840273944362
139901,clarke quay,1.29044567334676,103.84568804993799,tampines,1.35022823751066,103.928412800091
139886,clementi,1.2963298251589699,103.7676022071,woodlands,1.41520591465648,103.758554325238
139876,bishan,1.3596538482492302,103.832637290371,anywhere,nil
139891,clarke quay,1.29044567334676,103.84568804993799,bedok,1.32368201682055,103.947789319297
139911,clarke quay,1.29044567334676,103.84568804993799,520914,1.3490277706321698,103.939568394541
139871,hougang,1.3799438359273999,103.887465509279,clarke quay,1.29044567334676,103.84568804993799
139906,821227,1.40358925655809,103.892958748314,370035,1.3291589969451,103.886010316123
139896,jurong,1.34390440884759,103.766254087753,anywhere,nil
139852,tampines,1.35022823751066,103.928412800091,town,1.30923241301234,103.842649053422

139862,pasir ris,1.3799565415449098,103.96361889803002,jurong,1.34390440884759,103.766254087753
139857,dempsey,1.30467342053312,103.809040024736,punggol,1.40546002750829,103.898354203231
139882,concorde hotel,1.30061922274712,103.84222854750799,clementi,1.2963298251589699,103.7676022071
139917,zouk,nil,yishun,1.41694678230154,103.845000884876
139867,changi airport t2,1.35546339989429,103.98927682118799,520165,1.3455301612006798,103.959248804134
139922,clarke quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
139887,liang court clarke quay,nil,27 prince george’s park,nil
139877,hong kah point,1.3498355389581298,103.719020953125,670502,1.3837172129332802,103.76675082813802
139902,clarke quay,1.29044567334676,103.84568804993799,bukit batok,1.3508238085532098,103.73826825406601
139912,jalan besar,1.3117825538737098,103.859466732217,sengkang,1.38315380470819,103.89238167637801
139872,punggol,1.40546002750829,103.898354203231,upper thomson,1.39758106126826,103.817856949947
139907,jurong,1.34390440884759,103.766254087753,woodlands,1.41520591465648,103.758554325238
139897,hougang,1.3799438359273999,103.887465509279,ang mo kio,1.3687783887791,103.840273944362
139892,novotel clarke quay,1.2915147818883799,103.84458629833,teow chew cuising restaurant,nil
139853,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139863,bukit batok,1.3508238085532098,103.73826825406601,town,1.30923241301234,103.842649053422
139858,town,1.30923241301234,103.842649053422,yishun sembawang woodland,nil
139883,clark quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
139918,sengkang,1.38315380470819,103.89238167637801,jurong,1.34390440884759,103.766254087753
139868,suntec,1.2954667558967499,103.858585026016,marine parade,1.3028676454890702,103.90483750033701
139903,river valley road,1.29558337669446,103.83773442378799,520914,1.3490277706321698,103.939568394541
139923,novotel,1.2915147818883799,103.84458629833,786b woodlands drive 60,1.44568798991504,103.80069395076
139878,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139873,suntec convention centre,1.2936221622883302,103.857252816966,jurong west and taman jurong,nil
139888,liang court clarke quay,nil,2d upper boon keng road,1.3130792767173898,103.872380169741
139913,orchard gateway,1.30044325279546,103.839442780042,20 choa chu kang street 64,1.39774827163463,103.751580705894
139898,novotel,1.2915147818883799,103.84458629833,521164,1.3496215142655,103.946000691097
139908,novotel clarke quay,1.2915147818883799,103.84458629833,ntu hall 5,1.34616863877198,103.679965382245
139893,zouk,nil,yishun,1.41694678230154,103.845000884876
139854,d underground,nil,640427,1.3513137356609801,103.725596710632
139864,clementi,1.2963298251589699,103.7676022071,town,1.30923241301234,103.842649053422
139884,689686,1.3865270994070402,103.743341984317,sengkang,1.38315380470819,103.89238167637801
139914,punggol,1.40546002750829,103.898354203231,upper thomson,1.39758106126826,103.817856949947
139859,kampong glam cafe bussorah street,nil,kimseng road great world city,nil
139919,orchard gateway,1.30044325279546,103.839442780042,20 choa chu kang street 64,1.39774827163463,103.751580705894
139874,yishun,1.41694678230154,103.845000884876,jurong,1.34390440884759,103.766254087753
139924,liang court novotel,nil,buangkok,1.3808237249315602,103.892119365703
139879,clark quay central,nil,choa chu kang,1.4038469560746203,103.749878668123
139904,arab street,1.3016643832592498,103.85884555445699,hougang,1.3799438359273999,103.887465509279
139889,460102,1.33390654765002,103.937458398204,535986,1.3829865639907601,103.880472549781
139899,jurongwest,nil,pioneer,1.3085131714795701,103.674623963707
139869,pan pacific hotel,1.29241443325541,103.858814384016,jurong west and taman jurong,nil
139894,bukit batok,1.36053358595052,103.74236455589701,clementi,1.2963298251589699,103.7676022071
139909,clarke quay,1.29044567334676,103.84568804993799,anywhere ard north east,nil
139855,507020,1.38100673268096,103.96412150185101,560302,1.36708983179046,103.845660199054
139865,punggol,1.40546002750829,103.898354203231,upper thomson,1.39758106126826,103.817856949947
139885,liang court clarke quay,nil,ntu hall 5,1.3504860878345302,103.681819176774
139915,novetel,nil,hougang,1.3799438359273999,103.887465509279
139925,yishun,1.41694678230154,103.845000884876,btbatok,nil
139860,changi airport t2,1.35546339989429,103.98927682118799,520165,1.3455301612006798,103.959248804134
139920,jalan besar,1.3117825538737098,103.859466732217,sengksng,nil
139890,clementi,1.2963298251589699,103.7676022071,woodlands,1.41520591465648,103.758554325238
139905,town,1.30923241301234,103.842649053422,ang mo kio,1.3687783887791,103.840273944362
139880,liang court novotel,nil,buangkok,1.3808237249315602,103.892119365703
139895,jurong west,1.34160326621595,103.70808518963301,pasir ris street 72,1.3803522624156999,103.936599897195
139910,198 punggol field,1.39948071650135,103.906392994106,110001,1.2852720836574498,103.77911681059099
139900,310100,1.3395640051788502,103.848585713817,560562,1.37018144221922,103.85901883576
139926,orchard gateway,1.30044325279546,103.839442780042,20 choa chu kang street 64,1.39774827163463,103.751580705894
139870,boat quay,1.2881578742698,103.849373215384,ang mo kio,1.3687783887791,103.840273944362
139931,liang court,1.29149019892639,103.84466893511299,punggol,1.40546002750829,103.898354203231
139936,clarke quay,1.29044567334676,103.84568804993799,bedok,1.32368201682055,103.947789319297
139941,punggol,1.40546002750829,103.898354203231,upper thomson,1.39758106126826,103.817856949947
139946,clark quay,1.29044567334676,103.84568804993799,sengkang,1.38315380470819,103.89238167637801
139971,bt panjang,1.3775072762462,103.77360557644,jurong east,1.34063904358364,103.742474504127
139961,novohotel,nil,sweechoon,nil
139956,suntec city tower 5 pick up,nil,toa payoh yio chu kang,nil
139951,clarke quay,1.29044567334676,103.84568804993799,sengkang,1.38315380470819,103.89238167637801
139976,clarke quay,1.29044567334676,103.84568804993799,woodlands,1.41520591465648,103.758554325238
139981,liang court,1.29149019892639,103.84466893511299,woodlands,1.41520591465648,103.758554325238
139966,clarke quay,1.29044567334676,103.84568804993799,ang mo kio avenue 5,1.37583949600191,103.854640743205
139927,liang court novotel,nil,punggol and fernvale,nil
139986,changi airport,1.3563414213584501,103.989276642386,north east,1.32359123714089,103.878812083172
139991,yishun,1.41694678230154,103.845000884876,novotel clarke quay,1.2915147818883799,103.84458629833
139937,520372,1.3564421453905902,103.95809563794201,520266,1.35196574894384,103.950237717969
139932,orchard gateway,1.30044325279546,103.839442780042,20 choa chu kang street 64,1.39774827163463,103.751580705894
139972,suntec,1.2954667558967499,103.858585026016,woodlands,1.41520591465648,103.758554325238
139962,jurong,1.34390440884759,103.766254087753,anywhere,nil
139942,liang court novotel,nil,730308,1.4298042238310802,103.77656072564699
139947,clarke quay,1.29044567334676,103.84568804993799,520914,1.3490277706321698,103.939568394541
139977,clarke quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
139992,clarke quay,1.29044567334676,103.84568804993799,anywhere,nil
139952,yishun,1.41694678230154,103.845000884876,jurong,1.34390440884759,103.766254087753
139957,simpang bedok,1.33367770451888,103.945745989689,tampines,1.35022823751066,103.928412800091
139928,hougang,1.3799438359273999,103.887465509279,circuit rd,1.32918048555782,103.88547007975599
139967,clarke quay,1.29044567334676,103.84568804993799,choa chu kang,1.4038469560746203,103.749878668123
139982,yishun,1.41694678230154,103.845000884876,jb,nil
139987,liang court,1.29149019892639,103.84466893511299,woodlands,1.41520591465648,103.758554325238
139875,choa chu kang north 6,1.3962396276256002,103.748294283534,choa chu kang avenue 4,1.38238842100533,103.74019578188
139938,liang court,1.29149019892639,103.84466893511299,punggol,1.40546002750829,103.898354203231
139933,read crescent park clarke quay,nil,bukit batok,1.36053358595052,103.74236455589701

139953,22 jln nipah,1.3258968012664298,103.953196258604,670434,1.38545924836708,103.77050511556999
139948,clarke quay,1.29044567334676,103.84568804993799,woodlands,1.41520591465648,103.758554325238
139968,clarke quay,1.29044567334676,103.84568804993799,woodlands,1.41520591465648,103.758554325238
139943,hougang,1.3799438359273999,103.887465509279,circuit rd,1.32918048555782,103.88547007975599
139978,clarke quay,1.29044567334676,103.84568804993799,ang mo kio avenue 5,1.37583949600191,103.854640743205
139963,liang court,1.29149019892639,103.84466893511299,punggol,1.40546002750829,103.898354203231
139958,clarke quay,1.29044567334676,103.84568804993799,bedok,1.32368201682055,103.947789319297
139929,zouk,nil,lakeside mrt &amp; teck whye lrt,nil
139993,520356,1.3544006655143201,103.961454818751,changi airport t2 departure,nil
139973,woodlands,1.41520591465648,103.758554325238,jurong,1.34390440884759,103.766254087753
139988,bugis,1.29950761348254,103.854370864874,sengkang,1.38315380470819,103.89238167637801
139983,liang court,1.29149019892639,103.84466893511299,bukit panjang,1.3775072762462,103.77360557644
139996,changi service club 30 netheravon road,nil,jalan pernama and tampines st 32,nil
139939,choa chu kang,1.4038469560746203,103.749878668123,west side,nil
139934,liang court novotel,nil,760122,1.43499758920057,103.831124796378
139959,clarke quay,1.29044567334676,103.84568804993799,680112,1.37748545136823,103.751921303308
139930,clarke quay,1.29044567334676,103.84568804993799,520914,1.3490277706321698,103.939568394541
139954,liang court,1.29149019892639,103.84466893511299,scape,1.30086543586584,103.83570084035699
139969,serangoon,1.3448920150304198,103.87125222941201,choa chu kang,1.4038469560746203,103.749878668123
139944,clark quay,1.29044567334676,103.84568804993799,680112,1.37748545136823,103.751921303308
139979,liang court,1.29149019892639,103.84466893511299,punggol,1.40546002750829,103.898354203231
139964,choa chu kang,1.4038469560746203,103.749878668123,west side,nil
139989,clarke quay,1.29044567334676,103.84568804993799,east,1.3108349867393,103.92171580265999
139949,520372,1.3564421453905902,103.95809563794201,520266,1.35196574894384,103.950237717969
139997,yishun,1.41694678230154,103.845000884876,sengkang,1.38315380470819,103.89238167637801
139984,liang court,1.29149019892639,103.84466893511299,punggol,1.40546002750829,103.898354203231
139994,clarke quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
139974,zouk,nil,yishun,1.41694678230154,103.845000884876
139940,088854,1.2791046779611102,103.84170181008699,jelapang road,1.38487004798316,103.766702197136
139935,jurong west,1.34160326621595,103.70808518963301,pasir ris street 72,1.3803522624156999,103.936599897195
139965,clarke quay,1.29044567334676,103.84568804993799,640520,1.34609883764929,103.717876373079
140001,488829,1.32592332741719,103.953261215349,460545,1.3300514240201,103.92411803142299
139980,liang court,1.29149019892639,103.84466893511299,510478,1.3744937684235599,103.958958334109
139970,jurong,1.34390440884759,103.766254087753,anywhere,nil
139955,keat hong,1.37754385007464,103.74970003670099,lucky plaza,1.30446378974741,103.834005158524
139950,suntec tower 1 2,nil,yishun,1.41694678230154,103.845000884876
139990,suntec,1.2954667558967499,103.858585026016,woodlands,1.41520591465648,103.758554325238
139998,suntec tower 5 lobby 1,nil,marine parade,1.3028676454890702,103.90483750033701
139945,clark quay,1.29044567334676,103.84568804993799,lakeside mrt,1.3439874151181699,103.720437685172
139960,orchard,1.3026182214637099,103.829383494413,ang mo kio,1.3687783887791,103.840273944362
139985,novtel hotel,nil,woodlands,1.41520591465648,103.758554325238
139975,clarke quay,1.29044567334676,103.84568804993799,teck whye,1.38012990422533,103.758203987241
140006,hougang avenue 10,1.3748677991054499,103.895137152932,bukit merah view,1.28326467654878,103.823800585999
139995,geylang lobang 18,nil,760618,1.4187353006021002,103.83570328066901
140011,geylang lobang 18,nil,760618,1.4187353006021002,103.83570328066901
140026,clarke quay,1.29044567334676,103.84568804993799,tampines,1.35022823751066,103.928412800091
140021,novotel,1.2915147818883799,103.84458629833,woodlands,1.41520591465648,103.758554325238
140002,geylang lobang 18,nil,760618,1.4187353006021002,103.83570328066901
140016,clarke quay,1.29044567334676,103.84568804993799,tampines,1.35022823751066,103.928412800091
139999,clarke quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
139770,63 tanjong pagar,1.2782699195602099,103.843963149811,640725,1.34545354960103,103.69771962383601
139775,51 kent road,1.3167570723148,103.85110555793399,150125,1.28593366735428,103.80299973798799
139760,prinsep st,1.29970274449064,103.849886983698,tampines,1.35022823751066,103.928412800091
139765,scape pick up point,nil,the mask,nil
140031,bukit panjang,1.3775072762462,103.77360557644,ang mo kio,1.3687783887791,103.840273944362
140007,liang court,1.29149019892639,103.84466893511299,640402,1.3533936597147,103.72244565465401
140012,liang court,1.29149019892639,103.84466893511299,sengkang,1.38315380470819,103.89238167637801
140027,liang court,1.29149019892639,103.84466893511299,hg sk punggol,nil
140003,sweechoon,nil,yishun,1.41694678230154,103.845000884876
140022,novotel,1.2915147818883799,103.84458629833,822666,1.40179672508932,103.915278092564
140017,bukit panjang,1.3775072762462,103.77360557644,ang mo kio,1.3687783887791,103.840273944362
140000,liang court,1.29149019892639,103.84466893511299,choa chu kang,1.4038469560746203,103.749878668123
139771,sembawang,1.4505243561844299,103.829006229545,sengkang,1.38315380470819,103.89238167637801
139766,clarke quay,1.29044567334676,103.84568804993799,commonwealth,1.29556628401854,103.806204356557
139761,woodlands,1.41520591465648,103.758554325238,anywhere,nil
139756,clarke quay,1.29044567334676,103.84568804993799,serangoon,1.3448920150304198,103.87125222941201
140013,jurong,1.34390440884759,103.766254087753,249720,1.30619917173786,103.827947339494
140008,clarke quay,1.29044567334676,103.84568804993799,bukit panjang,1.3775072762462,103.77360557644
140004,swee choon,nil,350113,1.33605593871889,103.86359950782801
140028,sweechoon,nil,yishun,1.41694678230154,103.845000884876
140023,jurong,1.34390440884759,103.766254087753,249720,1.30619917173786,103.827947339494
140018,jurong,1.34390440884759,103.766254087753,249720,1.30619917173786,103.827947339494
139772,63 tanjong pagar,1.2782699195602099,103.843963149811,640725,1.34545354960103,103.69771962383601
140014,bukit panjang,1.3775072762462,103.77360557644,ang mo kio,1.3687783887791,103.840273944362
139757,sengkang,1.38315380470819,103.89238167637801,woodlands,1.41520591465648,103.758554325238
139767,telok blangah,1.27719316643926,103.80725670487,anywhere,nil
139762,jurong west,1.34160326621595,103.70808518963301,pasir ris street 72,1.3803522624156999,103.936599897195
140009,geylang lor 29,1.3154067360988602,103.885598240069,610156,1.32789040951674,103.72178882685999
140005,concorde hotel,1.30061922274712,103.84222854750799,120421,1.3090979870290802,103.76835591305401
140024,600335,1.35021953451852,103.73216274594601,lee wee nam library ntu,nil
140029,choa chu kang,1.4038469560746203,103.749878668123,jurong west,1.34160326621595,103.70808518963301
140019,concorde hotel,1.30061922274712,103.84222854750799,clementi,1.2963298251589699,103.7676022071
139773,choa chu kang bukit batok yew tee,nil,anywhere,nil
139768,woodlands,1.41520591465648,103.758554325238,choa chu kang,1.4038469560746203,103.749878668123
140015,liang court,1.29149019892639,103.84466893511299,sengkang,1.38315380470819,103.89238167637801
139758,prinsep st,1.29970274449064,103.849886983698,246 compassvale rd,1.39254395356624,103.899041774365
140010,geylang lor 29,1.3154067360988602,103.885598240069,610156,1.32789040951674,103.72178882685999
139763,clarke quay,1.29044567334676,103.84568804993799,clementi,1.2963298251589699,103.7676022071
140025,novotel,1.2915147818883799,103.84458629833,768861,1.42477003544275,103.84805359190901
140030,jurong,1.34390440884759,103.766254087753,249720,1.30619917173786,103.827947339494
139774,jurong,1.34390440884759,103.766254087753,pasir ris,1.3799565415449098,103.96361889803002

139769,safra punggol,1.4101948880134298,103.906072212007,haqinsaf,nil
140020,novotel,1.2915147818883799,103.84458629833,tampines,1.35022823751066,103.928412800091
139759,holland village,1.31114806173831,103.795003427542,pasir panjang,1.30824908081028,103.763318217537
139764,369520,1.3356784478869,103.88623773830601,799264,1.3994759025236598,103.871327058375
time:  0:00:15.212309

In [ ]:
# Get lat-long of location pick_up_clean and drop_off_clean
def get_address_2(row_index):
    time.sleep(0.1)
    #-----PARAMETERS------
    HEADER = {'User-Agent': random.choice(HEADERS_LIST)}
    proxy = next(proxy_pool)
    #---------------------
    
    pick_up_geo = "nil"
    drop_off_geo = "nil"
    
    if bool(re.search(r'\d{6}', data_normalised.iloc[row_index]['pick_up_clean'])):
        pu_location = re.search(r'\d{6}', data_normalised.iloc[row_index]['pick_up_clean']).group()
    else:
        pu_location = data_normalised.iloc[row_index]['pick_up_clean']
    onemap_url = "https://developers.onemap.sg/commonapi/search"
    onemap_params = {'searchVal' : pu_location, 'returnGeom' : "Y", 'getAddrDetails' : "Y"}
    r = requests.get(url = onemap_url, params = onemap_params, headers=HEADER, proxies={"http": proxy}, timeout=60)
    data = r.json()
    try:
        lat = data['results'][0]['LATITUDE']
        long = data['results'][0]['LONGTITUDE']
        lat_long = lat+","+long
        pick_up_geo = lat_long
    except:
        pass
    
    if bool(re.search(r'\d{6}', data_normalised.iloc[row_index]['drop_off_clean'])):
        do_location = re.search(r'\d{6}', data_normalised.iloc[row_index]['drop_off_clean']).group()
    else:
        do_location = data_normalised.iloc[row_index]['drop_off_clean']
    onemap_params = {'searchVal' : do_location, 'returnGeom' : "Y", 'getAddrDetails' : "Y"}
    r = requests.get(url = onemap_url, params = onemap_params, headers=HEADER, proxies={"http": proxy}, timeout=60)
    data = r.json()
    try:
        lat = data['results'][0]['LATITUDE']
        long = data['results'][0]['LONGTITUDE']
        lat_long = lat+","+long
        drop_off_geo = lat_long
    except:
        pass
    
    result_string = str(row_index)+","+pu_location+","+pick_up_geo+","+do_location+","+drop_off_geo
    
    f = open("./data/geoloc_2.txt", "a")
    f.write("%s\n" %result_string)
    print(result_string)
    return pd.DataFrame([[row_index, pu_location, pick_up_geo, do_location, drop_off_geo]], columns=['index', 'pick_up_loc', 'pick_up_geo', 'drop_off_loc', 'drop_off_geo'])

proxies = get_proxies()
proxy_pool = cycle(proxies)

start = datetime.now()
with Pool(15) as p:
    result = p.map(get_address_2, range(50000,100000))
print("time: ", datetime.now()-start)

data_geocode_2 = pd.concat(result)

In [66]:
data_geocode

,index,pick_up_loc,pick_up_geo,drop_off_loc,drop_off_geo
0,50000,jurong west,"1.34160326621595,103.70808518963301",pasir ris,"1.3799565415449098,103.96361889803002"
0,50001,kent ridge,"1.2811408094543002,103.79006809153",seletar,"1.38444835264519,103.875922179356"
0,50002,hougang,"1.3799438359273999,103.887465509279",bedok,"1.32368201682055,103.947789319297"
0,50003,dhoby ghaut,"1.29974847075063,103.84537229400401",marsiling,"1.4401773951163999,103.776496871681"
0,50004,bukit panjang,"1.3775072762462,103.77360557644",tampinese,nil
...,...,...,...,...,...
0,99995,cuppage,"1.3021555073451,103.840293633443",yewtee,"1.3970587735697702,103.746643983707"
0,99996,pasir ris,"1.3799565415449098,103.96361889803002",woodlands,"1.41520591465648,103.758554325238"
0,99997,serangoon,"1.3448920150304198,103.87125222941201",buangkok,"1.3808237249315602,103.892119365703"
0,99998,tampines,"1.35022823751066,103.928412800091",clarke quay,"1.29044567334676,103.84568804993799"
0,99999,520465,"1.3595871513452602,103.95466415545602",548935,"1.35696955009812,103.878711621962"

In [69]:
geo.sort_values('row_index')

,row_index,pick_up_location,pu_lat,pu_long,drop_off_location,do_lat,do_long
8,0,tuas,1.3190226400254899,103.63656583171499,bedok reservoir,1.34231030001047,103.925858
26,1,up - mountbatten mrt,nil,off - ntu,nil,NaN,NaN
37,2,bedok,1.32368201682055,103.947789319297,north-east,nil,NaN
52,3,jurong,1.34390440884759,103.766254087753,north-east or east,nil,NaN
67,4,jurong west,1.34160326621595,103.70808518963301,suss,1.3136407681546398,103.790066
...,...,...,...,...,...,...,...
99466,99995,cuppage,1.3021555073451,103.840293633443,yewtee,1.3970587735697702,103.746644
99480,99996,pasir ris,1.3799565415449098,103.96361889803002,woodlands,1.41520591465648,103.758554
99495,99997,serangoon,1.3448920150304198,103.87125222941201,buangkok,1.3808237249315602,103.892119
99514,99998,tampines,1.35022823751066,103.928412800091,clarke quay,1.29044567334676,103.845688
99529,99999,520465,1.3595871513452602,103.95466415545602,548935,1.35696955009812,103.878712